[build]
  command = "hugo"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.55.6"
  HUGO_ENABLEGITINFO = "false" # 20190601 set to true originally but this prevents the variable lastmod from being used

[context.production.environment]
  HUGO_ENV = "production"
